# Generated by Django 4.0.3 on 2022-03-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100)),
                ('article_abstract', models.TextField(blank=True, null=True)),
                ('article_content', models.TextField()),
                ('article_post_time', models.DateTimeField(auto_now=True)),
                ('article_status', models.SmallIntegerField(choices=[(0, '审核中'), (1, '已发布'), (2, '审核失败')], default=0)),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.author')),
            ],
        ),
    ]
