# Generated by Django 4.0.3 on 2022-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_abstract',
            field=models.TextField(),
        ),
    ]
