# Generated by Django 4.0.3 on 2022-03-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_alter_article_article_abstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_abstract',
            new_name='article_description',
        ),
    ]
